# Generated by Django 4.2.27 on 2025-12-12 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['categoria'],
                'get_latest_by': 'criado_em',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitulo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('publicado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Actualização')),
                ('status', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.categoria')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'db_table': 'noticias',
                'ordering': ['-publicado_em'],
                'permissions': [('pode_publicar', 'Pode publicar notícias')],
                'get_latest_by': 'publicado_em',
            },
        ),
    ]
