# Generated by Django 5.2.7 on 2026-02-03 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_evento_alter_noticia_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='vagas',
            field=models.IntegerField(default=50, verbose_name='Número de Vagas'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='exclusivo_alunos',
            field=models.BooleanField(default=False, verbose_name='Exclusivo para Alunos'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_estudante', models.CharField(max_length=20, unique=True, verbose_name='Número de Estudante')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('ano_ingresso', models.IntegerField(verbose_name='Ano de Ingresso')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/uploads/alunos/', verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='pages.aluno')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='pages.evento')),
            ],
            options={
                'verbose_name': 'Inscrição em Evento',
                'verbose_name_plural': 'Inscrições em Eventos',
                'ordering': ['-data_inscricao'],
                'unique_together': {('aluno', 'evento')},
            },
        ),
    ]
