# Generated by Django 5.2.7 on 2026-02-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_evento_vagas_noticia_exclusivo_alunos_aluno_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricaoevento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='evento',
            name='exclusivo_alunos',
            field=models.BooleanField(default=True, verbose_name='Exclusivo para Alunos'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='email_externo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Externo)'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='nome_externo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome (Externo)'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='telefone_externo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (Externo)'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='pages.aluno'),
        ),
    ]
