# Generated by Django 5.2.7 on 2026-03-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_aluno_nome_alter_aluno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/events/', verbose_name='Imagem'),
        ),
    ]
