"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gl_%8gqt=w_c-x6lqi7jocm+6gq^+czcnysn7g^a3zpj9w%xzy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages.apps.PagesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'projecto_fim_curso.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-ao'

TIME_ZONE = 'Africa/Luanda'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,STATIC_URL)
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {
    "site_title": "Painel Administrativo",
    "site_header": "Painel de Noticias do  IPM",
    "site_brand": "IPM Noticias",
    "site_logo": "images/favicon.ico",  # Coloque em static/images
    "login_logo": "images/favicon.ico",
    "login_logo_dark": None,
        # Permitir que usuários mudem tema pelo Admin
    "show_ui_builder": True,   # MOSTRA a ferramenta de UI para estilizar
    "theme": None,             # deixa sem tema definido por código
    # Texto da página de login
    "welcome_sign": "Bem-vindo ao painel administrativo!",
    "copyright": "© 2025 Grupo Numero 6 ",

    # ***** CORES E TEMA *****
    "theme": "darkly",  # ou: flatly, cyborg, journal, lumen, pulse...

    # Layout do sidebar
    "sidebar": "dark",  # light | dark
    "navigation_expanded": True,

    # ***** ÍCONES DE MODELOS *****
    "icons": {
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "pages.Noticia": "far fa-newspaper",
        "pages.Categoria": "fas fa-tags",
    },

    # ***** MENU CUSTOMIZADO *****
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "auth"},  # mostra o app auth
        {"name": "Site", "url": "/", "new_window": True},
    ],

    "side_menu": {
        "show_app_icons": True,
        "hide_apps": ["sessions"],
        "hide_models": ["auth.Permission"], 
    },

    # ***** ORDEM DOS APPS NO MENU *****
    "order_with_respect_to": [
        "pages",
        "auth",
    ],
}

# ***** CUSTOMIZAÇÕES AVANÇADAS *****
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": True,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
        "warning": "btn-outline-warning",
        "info": "btn-info"
    },
    "brand_color": "#4CAF50",
    "sidebar_bg": "#1e1e2f",
    "sidebar_color": "#ffffff",
    "sidebar_hover": "#2e2e48",
    "sidebar_link_color": "#ffffff",
    "actions_sticky_top": True
}